### ISSUE TITLE
opera GX

### ISSUE THREAD

**Issue by Lomusire** [NorthernChicken/MineInstall#1]
sry for creating a issue here but didn't knew how else to write you. Opera GX didn't end the promotion but changed there structure hes a working opera nitro link gen https://replit.com/@Lomusire/opera-new-gggpt4#main.py

**Comment by NorthernChicken** [comment]
okay sorry didn't realize that. Maybe the promotional servers were just down when I tried to ping them. My bad!

**Comment by Lomusire** [comment]
The developers of opera have recently made login a requirement and have also modified their API endpoint for token generation. However, this can be easily bypassed by using a session token due to the lack of rate limiting on the number of tokens generated per session. I was able to create a new, functional generator within 5 minutes, but it's not fully optimized. Feel free to fork the project and make any changes or improvements you see fit.
